var friends = [
    {
       "name":"Hayden",
       "photo":"https:",
       "scores":[
          "5",
          "1",
          "4",
          "4",
          "5",
          "1",
          "2",
          "5",
          "4",
          "1"
       ]
    },
    {
       "name":"Johnny",
       "photo":"https:"[
          "4",
          "2",
          "5",
          "1",
          "3",
          "2",
          "2",
          "1",
          "3",
          "2"
       ]
    },
    {
       "name":"Lisa",
       "photo":"https:",
       "scores":[
          "5",
          "2",
          "2",
          "2",
          "4",
          "1",
          "3",
          "2",
          "5",
          "5"
       ]
    },
    {
       "name":"Loui",
       "photo":"https:"[
          "3",
          "3",
          "4",
          "2",
          "2",
          "1",
          "3",
          "2",
          "2",
          "3"
       ]
    },
     {
        "name":"Fred",
        "photo":"https:"[
           "4",
           "3",
           "4",
           "1",
           "5",
           "2",
           "5",
           "3",
           "1",
           "4"
        ]
     },
     {
        "name":"Kallie",
        "photo":"https:"[
           "4",
           "4",
           "2",
           "3",
           "2",
           "2",
           "3",
           "2",
           "4",
           "5"
        ]
     }
 
 ]
 module.exports = friends;